[package]
name = "idl-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
pest = { version="2.7.2" }
pest_derive = "2.7.2"
thiserror = "1.0.44"
